# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93f15d0b2a48525e5bde46a57849d184ecfee7ef36f355fbb0ebb2a259545fc13602d8d7a00736c84c985d95300d319aef079ca3fa9f33a714832021b14cd79a

test:
  secret_key_base: dbee8f30ac746710945748d4f159d392ae69e02d022398fc3776195011f6cfcc5649a48a7d5e0d69abd26e9d397e6de7669a960abf3df55dad4b7ed25c972937

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
